version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: database
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
